version: '3.9'
services:
  # src:
  #   depends_on:
  #     - db
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   image: shopit:v1.0
  #   volumes:
  #     - ./app:/app
  #   env_file:
  #     - /src/.env
  #   ports:
  #     - 8000:8000
  #   command: sh -c "python manage.py migrate && \
  #                   python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:15.3
    restart: always
    command: -p 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data/
    env_file:
      - /src/.env


volumes:
  postgres_data: